import type { user } from "../schema/core/user";
import type { character } from "../schema/gameplay/character";
import type { characterItem } from "../schema/gameplay/characterItem";
import type { characterQuest } from "../schema/gameplay/characterQuest";
import type { characterResource } from "../schema/gameplay/characterResource";
import type { characterAttribute } from "../schema/gameplay/characterAttribute";
import type { characterStatusEffect } from "../schema/gameplay/characterStatusEffect";
import type { characterLocation } from "../schema/map/characterLocation";
import type { characterFaction } from "../schema/social/characterFaction";
import type { characterAchievement } from "../schema/world/characterAchievement";
import type { characterFacility } from "../schema/world/characterFacility";
import type { characterRecipe } from "../schema/world/characterRecipe";
import type { characterEquipment } from "../schema/gameplay/characterEquipment";
import type { logEntry } from "../schema/core/log";
import type { session } from "../schema/core/session";
import type { combatEncounter } from "../schema/gameplay/combat";
import type { enemy } from "../schema/gameplay/enemy";
import type { event } from "../schema/gameplay/event";
import type { item } from "../schema/gameplay/item";
import type { quest } from "../schema/gameplay/quest";
import type { resource } from "../schema/gameplay/resource";
import type { attribute } from "../schema/gameplay/attribute";
import type { statusEffect } from "../schema/gameplay/statusEffect";
import type { location } from "../schema/map/location";
import type { region } from "../schema/map/region";
import type { dialog } from "../schema/social/dialog";
import type { dialogOption } from "../schema/social/dialogOption";
import type { faction } from "../schema/social/faction";
import type { achievement } from "../schema/world/achievement";
import type { calendarEvent } from "../schema/world/calendar";
import type { facility } from "../schema/world/facility";
import type { facilityUpgrade } from "../schema/world/facilityUpgrade";
import type { recipe } from "../schema/world/recipe";
import type { recipeIngredient } from "../schema/world/recipeIngredient";
import type { worldState } from "../schema/world/worldState";
import type { role } from "../schema/core/role";
import type { permission } from "../schema/core/permission";
import type { rolePermission } from "../schema/core/rolePermission";
import type { blogPost } from "../schema/blog/blogPost";

export type User = typeof user.$inferSelect;
export type Character = typeof character.$inferSelect;
export type CharacterResource = typeof characterResource.$inferSelect;
export type CharacterItem = typeof characterItem.$inferSelect;
export type CharacterQuest = typeof characterQuest.$inferSelect;
export type CharacterFacility = typeof characterFacility.$inferSelect;
export type CharacterFaction = typeof characterFaction.$inferSelect;
export type CharacterAttribute = typeof characterAttribute.$inferSelect;
export type CharacterStatusEffect = typeof characterStatusEffect.$inferSelect;
export type CharacterRecipe = typeof characterRecipe.$inferSelect;
export type CharacterAchievement = typeof characterAchievement.$inferSelect;
export type CharacterLocation = typeof characterLocation.$inferSelect;
export type CharacterEquipment = typeof characterEquipment.$inferSelect;
export type Session = typeof session.$inferSelect;
export type Resource = typeof resource.$inferSelect;
export type Region = typeof region.$inferSelect;
export type Event = typeof event.$inferSelect;
export type Enemy = typeof enemy.$inferSelect;
export type CombatEncounter = typeof combatEncounter.$inferSelect;
export type Item = typeof item.$inferSelect;
export type Quest = typeof quest.$inferSelect;
export type Facility = typeof facility.$inferSelect;
export type FacilityUpgrade = typeof facilityUpgrade.$inferSelect;
export type Faction = typeof faction.$inferSelect;
export type Attribute = typeof attribute.$inferSelect;
export type Dialog = typeof dialog.$inferSelect;
export type DialogOption = typeof dialogOption.$inferSelect;
export type StatusEffect = typeof statusEffect.$inferSelect;
export type CalendarEvent = typeof calendarEvent.$inferSelect;
export type WorldState = typeof worldState.$inferSelect;
export type Recipe = typeof recipe.$inferSelect;
export type RecipeIngredient = typeof recipeIngredient.$inferSelect;
export type Achievement = typeof achievement.$inferSelect;
export type LogEntry = typeof logEntry.$inferSelect;
export type Location = typeof location.$inferSelect;
export type Role = typeof role.$inferSelect;
export type Permission = typeof permission.$inferSelect;
export type RolePermission = typeof rolePermission.$inferSelect;
export type BlogPost = typeof blogPost.$inferSelect;