import type { logEntry } from "../schema/core/log";
import type { player } from "../schema/core/user";
import type { session } from "../schema/core/session";
import type { combatEncounter } from "../schema/gameplay/combat";
import type { enemy } from "../schema/gameplay/enemy";
import type { event } from "../schema/gameplay/event";
import type { item } from "../schema/gameplay/item";
import type { playerItem } from "../schema/gameplay/characterItem";
import type { playerQuest } from "../schema/gameplay/characterQuest";
import type { playerResource } from "../schema/gameplay/characterResource";
import type { playerStat } from "../schema/gameplay/characterAttribute";
import type { playerStatusEffect } from "../schema/gameplay/characterStatusEffect";
import type { quest } from "../schema/gameplay/quest";
import type { resource } from "../schema/gameplay/resource";
import type { stat } from "../schema/gameplay/attribute";
import type { statusEffect } from "../schema/gameplay/statusEffect";
import type { location } from "../schema/map/location";
import type { playerLocation } from "../schema/map/playerLocation";
import type { region } from "../schema/map/region";
import type { dialog } from "../schema/social/dialog";
import type { dialogOption } from "../schema/social/dialogOption";
import type { faction } from "../schema/social/faction";
import type { playerFaction } from "../schema/social/playerFaction";
import type { achievement } from "../schema/world/achievement";
import type { calendarEvent } from "../schema/world/calendar";
import type { facility } from "../schema/world/facility";
import type { facilityUpgrade } from "../schema/world/facilityUpgrade";
import type { playerAchievement } from "../schema/world/playerAchievement";
import type { playerFacility } from "../schema/world/playerFacility";
import type { playerRecipe } from "../schema/world/playerRecipe";
import type { recipe } from "../schema/world/recipe";
import type { recipeIngredient } from "../schema/world/recipeIngredient";
import type { worldState } from "../schema/world/worldState";
import type { role } from "../schema/core/role";
import type { permission } from "../schema/core/permission";
import type { rolePermission } from "../schema/core/rolePermission";
import type { playerEquipment } from "../schema/gameplay/characterEquipment";


export type Session = typeof session.$inferSelect;
export type Player = typeof player.$inferSelect;
export type Resource = typeof resource.$inferSelect;
export type PlayerResource = typeof playerResource.$inferSelect;
export type Region = typeof region.$inferSelect;
export type Event = typeof event.$inferSelect;
export type Enemy = typeof enemy.$inferSelect;
export type CombatEncounter = typeof combatEncounter.$inferSelect;
export type Item = typeof item.$inferSelect;
export type PlayerItem = typeof playerItem.$inferSelect;
export type Quest = typeof quest.$inferSelect;
export type PlayerQuest = typeof playerQuest.$inferSelect;
export type Facility = typeof facility.$inferSelect;
export type FacilityUpgrade = typeof facilityUpgrade.$inferSelect;
export type PlayerFacility = typeof playerFacility.$inferSelect;
export type Faction = typeof faction.$inferSelect;
export type PlayerFaction = typeof playerFaction.$inferSelect;
export type Stat = typeof stat.$inferSelect;
export type PlayerStat = typeof playerStat.$inferSelect;
export type Dialog = typeof dialog.$inferSelect;
export type DialogOption = typeof dialogOption.$inferSelect;
export type StatusEffect = typeof statusEffect.$inferSelect;
export type PlayerStatusEffect = typeof playerStatusEffect.$inferSelect;
export type CalendarEvent = typeof calendarEvent.$inferSelect;
export type WorldState = typeof worldState.$inferSelect;
export type Recipe = typeof recipe.$inferSelect;
export type RecipeIngredient = typeof recipeIngredient.$inferSelect;
export type PlayerRecipe = typeof playerRecipe.$inferSelect;
export type Achievement = typeof achievement.$inferSelect;
export type PlayerAchievement = typeof playerAchievement.$inferSelect;
export type LogEntry = typeof logEntry.$inferSelect;
export type Location = typeof location.$inferSelect;
export type PlayerLocation = typeof playerLocation.$inferSelect;
export type Role = typeof role.$inferSelect;
export type Permission = typeof permission.$inferSelect;
export type RolePermission = typeof rolePermission.$inferSelect;
export type PlayerEquipment = typeof playerEquipment.$inferSelect;